name: Build-and-Zip (GitHub-only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      # Kodunda macOS Intel/Mojave kontrolü varsa CI’da bypass için:
      CI_ALLOW_NON_INTEL: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Optional smoke (main.py varsa)
        shell: bash
        run: |
          if [ -f main.py ]; then
            export CI_ALLOW_NON_INTEL=1
            python - <<'PY'
import os, runpy
os.environ["CI_ALLOW_NON_INTEL"] = "1"
try:
    runpy.run_path("main.py", run_name="__main__")
except SystemExit:
    pass
print("✅ Smoke OK")
PY
          else
            echo "No main.py found, skipping smoke."
          fi

      - name: Create source zip
        # KÖK dizini ziple; .git ve Actions klasörünü hariç tut
        run: |
          mkdir -p dist
          zip -r dist/project-source.zip . -x ".git/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-zip
          path: dist/project-source.zip
