name: Build TesTimaGeNB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v3

      - name: Python kur (3.10)
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test çalıştır (örnek)
        run: |
          echo "🚀 Program çalışıyor mu test ediliyor..."
          python --version
          python main.py --help || true
