name: Build-and-Zip (GitHub-only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      CI_ALLOW_NON_INTEL: "1"   # CI'da platform kısıtını bypass et

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Optional smoke (main.py varsa)
        run: |
          if [ -f main.py ]; then
            export CI_ALLOW_NON_INTEL=1
            # Heredoc kullanmadan, sadece yardım ekranını çalıştır.
            python main.py --help || true
            echo "✅ Smoke OK"
          else
            echo "No main.py found, skipping smoke."
          fi

      - name: Create source zip
        run: |
          mkdir -p dist
          # .git ve .github klasörlerini hariç tut
          zip -r dist/project-source.zip . -x ".git/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-zip
          path: dist/project-source.zip
